# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Weekly Nix Flake Update

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-nix-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Nix flake
        run: 'nix flake update'

      - name: Build passthru
        run: 'nix build ".#default.passthru.fetch-deps"'

      - name: Run passthru
        run: |
            set -o pipefail
            ./result | tee /tmp/passthru.txt
            cp /"$(cat /tmp/passthru.txt | grep " wrote lockfile to " | cut -d / -f 2-)" nix/deps.nix

      - name: Format
        run: 'nix develop --command alejandra .'

      - uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.BOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.BOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_committer_name: patrick-conscriptus
          git_committer_email: '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Create token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          # https://github.com/actions/create-github-app-token/issues/136
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6.1.0
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: Update Nix flake
          title: Weekly Nix flake update
          body: |
            This is an automated pull request to update the Nix flake.

            Changes:
            ```
            ${{ steps.create-diff.outputs.diff }}
            ```
          branch: nix-flake-update
          base: main
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
