# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
name: Weekly Nix Flake Update

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 every Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-nix-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@00199f951aeb9404028a6e4b95ad42546f73296a # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Nix flake
        run: 'nix flake update'

      - name: Build fetch-deps
        run: 'nix build ".#default.fetch-deps"'

      - name: Run fetch-deps
        run: |
            set -o pipefail
            ./result nix/deps.json

      - name: Format
        run: 'nix develop --command alejandra .'

      - name: Create token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        with:
          # https://github.com/actions/create-github-app-token/issues/136
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Raise pull request
        uses: Smaug123/commit-action@d34807f26cb52c7a05bbd80efe9f964cdf29bc87
        id: cpr
        with:
            bearer-token: ${{ steps.generate-token.outputs.token }}
            pr-title: "Upgrade Nix flake and deps"
            branch-name: "auto-pr"

      - name: Enable Pull Request Automerge
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: peter-evans/enable-pull-request-automerge@a660677d5469627102a1c1e11409dd063606628d # v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
